Homework
spacenail/Concurrency2 pull request #1
Opened 2021-12-04 19:26 UTC by spacenail

2021-12-07 15:40 UTC, efserg requested changes

2021-12-07 15:40 UTC, efserg commented on src/Car.java
> +        MainClass.END_OF_PREPARED.countDown();
Не надо так делать. Передавайте нужные объекты в конструкторе класса

2021-12-07 15:40 UTC, efserg commented on src/Car.java
> +            } else {
Это уже совсем не ООП, а что-то другое

2021-12-07 20:04 UTC, spacenail commented on src/Car.java
> +            } else {
Убрал статику и InstanceOf - все синхронизаторы вынесены в отдельный класс с приватными полями и геттерами, проверка на одновременный въезд в туннель перенесена в класс Tunnel

2021-12-07 20:05 UTC, spacenail commented on src/Car.java
> +        MainClass.END_OF_PREPARED.countDown();
Статик убрал

2021-12-08 16:19 UTC, efserg requested changes

2021-12-08 16:19 UTC, efserg commented on src/Concurrent.java
> +    private final Semaphore tunnel;
Зачем здесь использовать семафор? У вас ведь есть класс Tunnel, пусть внутри него доступ и разруливается

2021-12-08 18:37 UTC, spacenail commented on src/Concurrent.java
> +    private final Semaphore tunnel;
Перенес функционал в класс Tunnel

2021-12-11 18:01 UTC, closed without merging